### ISSUE TITLE
Look into gsuite for non-profits

### ISSUE THREAD

**Issue by devdumpling** [devdumpling/osca#11]
We need to apply for gsuite for nonprofits. I suspect this will need to be done through Linda. Once we have confirmation, we will want to do some setup. This card is for that setup.

**Comment by lukeburns** [comment]
- Organizations must be recognized by the IRS as tax-exempt 501(c)(3) organizations formed for charitable, educational, religious, literary, scientific, or other tax-exempt purposes. 
- Fiscally sponsored organizations are not eligible for Google for Nonprofits.
- Organizations, such as churches, that are automatically considered tax-exempt under group exemption must still obtain recognition of 501(c)(3) tax exemption from the IRS to qualify for the Google for Nonprofits program.
- Organizations must be validated by TechSoup.

https://www.google.com/nonprofits/eligibility/

**Comment by jrymart** [comment]
OSCA prime is not a 501(c)(3) (and won't be for the foreseeable future) so this is probably a nonstarter.

**Comment by lukeburns** [comment]
Do you think it would be problematic for OSCA Foundation to allocate accounts to students?

**Comment by jrymart** [comment]
no idea.  doesn't seem out of this world but a question for OSCA leadership and a lawyer

**Comment by lukeburns** [comment]
"Every member of OSCA is also a member of the OSCA Foundation" — if this is true, I'd expect there to be no prob!

**Comment by jrymart** [comment]
good point!  It is true.  You never can tell tho...
