### ISSUE TITLE
System for anybody in OSCA to create their own experiments

### ISSUE THREAD

**Issue by devdumpling** [devdumpling/osca#12]

**Comment by lukeburns** [comment]
- subdomains:
   - experiment.osca.coop for osca-wide projects
   - experiment.harkness.osca.coop for harkness-wide projects
- make auth easy to restrict experiments to OSCA members (public projects are good too)
- expose other OSCA-focused APIs for use in experiments?
   - eg work chart api to build a work chart constraint solver (need to get authorization scope right)
- proposal process?
   - maybe only need proposal to acquire a subdomain for the experiment. Would be nice if anyone could start an experiment without consent. 
   - archival process for unused subdomains to make room for future students
