### ISSUE TITLE
Algorithm implementation

### ISSUE THREAD

**Issue by lukeburns** [devdumpling/osca#17]
Some thoughts:

It might be beneficial to implement a deterministic algorithm that uses `entryId` (which is a random hash) for initial ordering of entries (before accounting for preferences, etc). This way, we can re-run the algorithm and get the same thing—a useful property for auditing lottery results _and_ for situations where the algorithm needs to be re-run, because someone had to be removed for whatever reason.

It should be a pure function that takes in lottery entries (pulled from the `lottery-entries` collection and and lottery metadata pulled from the `lotteries/{lotteryId}` document) and spits out results. It should filter out ineligible entries (to be returned with explanations for ineligibility) and return assignments.

```
runLottery = (lotteryEntries, lotteryMetadata) => (assignments, ineligible)
```

MIT Room Lottery Algorithm: https://ashdown.mit.edu/room-algorithm.php

- [ ] `/api/lottery/run`: create endpoint for algorithm runs.

**Comment by jrymart** [comment]
Love this  One thought, I think we should separate ordering and assignments, especially with the new system (w/r/t indeterminate number of co-ops) it will probably by helpful for the memsec to see a raw ordering as a fall back.  

i've heard reference to a doc describing the lottery?  I know there are lots of oddities that take it beyond straight preference ordering (All-OSCA, DLECs, FSCs, other positions that require specific co-ops but still might need to be in the lottery for housing vs dining).  I think it will be helpful to have the ability to export different stages of assignments for auditing purposes.
