### ISSUE TITLE
Create db schema

### ISSUE THREAD

**Issue by devdumpling** [devdumpling/osca#27]
Need to talk about schema for the DB

**Comment by lukeburns** [comment]
Currently we have two collections in (my copy of) [Firestore](https://firebase.google.com/docs/firestore): `lotteries` and `lottery-entries`. 

<img width="1154" alt="Screen Shot 2021-01-23 at 11 08 38 PM" src="https://user-images.githubusercontent.com/189068/105623656-3513c180-5dd0-11eb-9b79-feefc9cef07f.png">

Lottery entry IDs are deterministic hashes of entry data that ensure unique entries.

<img width="1157" alt="Screen Shot 2021-01-23 at 11 09 41 PM" src="https://user-images.githubusercontent.com/189068/105623658-36dd8500-5dd0-11eb-9d55-f630a8837999.png">

**Comment by lukeburns** [comment]
Now featuring users and user permissions:
<img width="1162" alt="Screen Shot 2021-01-24 at 11 39 30 AM" src="https://user-images.githubusercontent.com/189068/105641437-d46c9f00-5e38-11eb-8f55-243f831e76eb.png">
