### ISSUE TITLE
Setup security roles

### ISSUE THREAD

**Issue by devdumpling** [devdumpling/osca#32]
# Security Roles

In order to handle content editing for now, security roles need to be established. For simplicity,  I propose two roles:

1. Publisher -- Can edit in Tina CMS
2. Subscriber -- Normal user that can view content, but does not have access to TinaCMS

Questions that need answering:

- Should the roles be established at the github level or the site level? Since we login through github to make Tina edits, it feels like it should be at the github level? 

- What pages should be editable? What parts of those pages?

**Comment by lukeburns** [comment]
Roles like this will probably have to come after https://github.com/devdumpling/osca/issues/16, not to mention implementation of a PR system for non-tech users.

I still like the idea of anyone being able to fork, edit, and propose changes via Tina! If we decide to go this route, we probably just need a less conspicuous place for the edit button for now. Interested parties can see what happens. Those with Github will probably login and try editing, and learn that it created a fork and know what to do from there. Those without Github will probably think they just don't have permissions to edit, but down the line we be clearer that anyone can propose content changes and possibly build tools (PRs via consensus) to make this process more accessible.

**Comment by lukeburns** [comment]
Ok, the way we're currently handling this is simply with permissions assigned to each user in the database, rather than roles. This way "Subscribers" simply lack permissions to access Tina.

**Comment by lukeburns** [comment]
We're using JSON files in the repository as a local content database. Tina is rendering this content and providing a mechanism to edit a copy on a forked repo. If in edit mode, Tina pulling content from their fork instead of the production repo. This is handled by `getStaticProps`.
