### ISSUE TITLE
Create lottery page/component

### ISSUE THREAD

**Issue by devdumpling** [devdumpling/osca#7]
# Create lottery page

- Should show information about the lottery in detail
- Should allow logged in users to submit their lottery
- need to have discussion about whether or not users can change their submissions after they're done

**Comment by lukeburns** [comment]
Made some progress here. Also:
- [ ] Entry Form
   - [x] T# and Graduation Year (unless we can get https://github.com/devdumpling/osca/issues/16 and https://github.com/devdumpling/osca/issues/29 sorted in time)
   - [ ] Preferences, etc

**Comment by lukeburns** [comment]
Pulling T# and grad year from db, since #29 shouldn't be too challenging!
